sofa-framework/SofaPython3

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/tests/Simulation/Node.py
Binding was not wrapping BaseNode* into a Sofa.Core.Node()
> FIX getRoot()

- Plugin/src/SofaPython3/PythonFactory.cpp
The toPython method in PythonFactory has 2 purposes:
1. by looking into the Data's TypeInfo, determining which kind of data it should return: DataContainer / DataVectorString, DataString or a generic Data wrapper
2. store the kind of data to return in a map using as key the template type of that Data, in order to not have to figure out the wrapper to return next time a similar data is to be returned
the key used for this map was BaseData::GetClass()->templateName, which happens to always be an empty string (dunno what this variable is actually supposed to store, but in the case of Data, it's alwas an empty string for me....) Thus, if a data is detected to be a "DataString" for instance, this type will be stored in a map, under the key "" (emptyString), and the next time a data must be …
> FIX: Downcast of Data

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonEnvironment.h
- Plugin/src/SofaPython3/PythonTest.cpp
- Plugin/src/SofaPython3/SceneLoaderPY3.cpp
This way we can use default py::globals() if necessary without having to instantiate globals before calling the method
> ImportPlugin now takes a pointer to the globals

- CMake/SofaPython3Tools.cmake
- Plugin/CMakeLists.txt
The sized-deallocation flag was:
- set in PRIVATE of the target in the binding modules
- set in the CXX_FLAGS of the Plugin
- Not set in the tests, which led to compile errors on some setups.
This PR sets the flag in PUBLIC in the Plugin, which propagates to the bindings and the tests.
There should be no side-effects with having it public, except for the fact that you won't have to add it again manually in your plugins that depend on SP3 (such as SofaQtQuickGUI)
> ADD: sized-deallocation on test targets

- .github/workflows/ubuntu.yml
There it is, first GitHub action workflow. Only Ubuntu 18.04 for now.
This is fetching SOFA binaries from a Github action on my SOFA fork. I'll change it once we get an official way to get the master branch installation binaries.
> [test] Add a github workflow for building and testing on ubuntu

- Plugin/src/SofaPython3/PythonFactory.cpp
There was two problem:
- the array values should always be returned as non writable numpy array otherwise this breaks the consistency of the
data notification mecanism.
- the arrays were stored in a cache, to accelerate things, but there is bug in the cache logics, resulting in hard to
spot side effect...so now it is not using cache anymore.
EDIT: the bug was pointed by @StephaneCotin on gitter.
> [SofaPython3] The coder returning "values" out of Basedata is broken

- CMake/SofaPython3Tools.cmake
- CMakeLists.txt
For some reason, when using python 3 libs from XCode, the RPATH set by cmake wasn't matching the relative path of the cpython library. This change simply adds the standard XCode framework path to the RPath for both build and install binaries.
> [cmake] Add XCode framework to RPath on MacOS

- .github/workflows/ubuntu.yml
- bindings/Sofa/tests/Core/BaseData.py
Fix a bug where SOFA binaries was not always able to be pulled.
Remove unittest for in-place operations on readonly data containers
> Fix ubuntu CI

- CMake/SofaPython3Tools.cmake
- bindings/Sofa/tests/CMakeLists.txt
- bindings/SofaRuntime/tests/CMakeLists.txt
- bindings/SofaTypes/tests/CMakeLists.txt
This PR fixes link problem when trying to load SP3 from an installed package. It also fixes link problem from the tests executable in MacOS (this is required if we want a CI on MacOS).
Adding RPATHs is non-breaking, so this PR is pretty harmless.
> [cmake] Add installation RPATH of SP3 target dependencies.

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonEnvironment.h
When we load a c++ plugin it may be packaged with additional python files
(examples, libraries, or per plugin binding). These files should be visible from the python environment.
This is done by the added code that scans the plugin's directory and register any path matching the following patterns:
pluginName/lib/site-packages
pluginName/lib/python3/site-packages
This behavior was the implemented in the previous version of SofaPython and proved to be useful.
> [SofaPython3] Restore the plugins automatic loading of python libraries.

- .github/workflows/macos.yml
~~Depends on #19 , once merged, we should remove its ref from the macos workflow file before merging this PR.~~
Note: Bindings.Sofa.Tests is failing on MacOS due to a test creating a segmentation fault. If someone have some time to look into it, that would be very appreciated:
```
[INFO]    [SofaPython3] Importing module: BaseLink.py
test_read (BaseLink.Test) ... 
########## SIG 11 - SIGSEGV: segfault ##########
```
> Add a MacOS CI workflow

- CMakeLists.txt
The SP3_PYTHON_PACKAGES_DIRECTORY is set to 'site-packages' by default, and is prepend to the `build/lib` or `install/lib` to get the directoy path where python packages should be build or installed, respectively.
It was reported that having this cmake variable as a PATH type would sometime mess with the resulting absolute path, as we are concatenating two PATHs together.
This PR simply changes the type of  SP3_PYTHON_PACKAGES_DIRECTORY to a STRING cached variable.
> Change the SP3_PYTHON_PACKAGES_DIRECTORY cmake variable type to STRING

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ObjectFactory.cpp
stupid PR, but I didn't like having to call functions to access public attributes of ClassEntry, so I changed them to readonly properties.
Also, aliases and dataAlias probably didn't work before given their previous implementation
> changing attribute bindings of ObjectModel::ClassEntry

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseLink.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseLink.h
A function was implemented for getLinks, to retrieve a py::list from the binding, but it wasn't used. Also, the getLinkedBase method binding wasn't working
> [Binding.Sofa.Core] FIX Link bindings

- bindings/Sofa/tests/CMakeLists.txt
- bindings/Sofa/tests/Simulation/Simulation.py
Someone reported a bug on simulation.load. 
I noticed that there was not test for this binding so I added one.
> [SofaPython3/binding/Sofa] Add a first test for simulation.

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base_doc.h
I often have to change a lot of data field for the same object. 
This function allows to do that by using the kwargs to set name=value.
A quick example
```python
myobject.setDataValues(position=[1.0,2.0,3.0], 
velocity=[2.0,3.0, 4.0])
```
> [SofaPython3] Add a per-keyword setData function

- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Helper/Binding_MessageHandler.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Helper/Binding_MessageHandler.h
- bindings/Sofa/src/SofaPython3/Sofa/Helper/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Helper/Submodule_Helper.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
- bindings/Sofa/tests/Helper/Message.py
- bindings/Sofa/tests/Simulation/Node.py
- bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
This PR lets you write MessageHandlers in Python.
It also lets you instantiate them in a RAII way by taking advantage of Python3's context managers.
All you have to do is implement the process function in a MessageHandler-inherited python class (see diff in Message.py)
@damienmarchal @jnbrunet
> [Bindings.Sofa.Helper] Add MessageHandler context manager class

- Plugin/src/SofaPython3/Prefab.cpp
there was 3 different componentstates in SOFA before, it's been unified recently.
m_componentstate and d_componentstate dissapear, and we keep d_componentState.
> Fix componentState

- Plugin/src/SofaPython3/DataHelper.cpp
- Plugin/src/SofaPython3/DataHelper.h
- Plugin/src/SofaPython3/Prefab.cpp
- Plugin/src/SofaPython3/Prefab.h
- Plugin/src/SofaPython3/PythonFactory.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Prefab.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataLink.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataLink.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
Adding the possibility to create "PrefabLinks" on prefab components. Contrary to legacy links, PrefabLinks are:
- Only instantiable on prefabs (for now at least)
- Inheriting Data, thus can be added to callbacks, added to data groups, etc.
PrefabLinks are used to create blackbox-like interfaces for Sofa.Prefabs in the GUI, where Prefabs expose very visually their dependencies.
> ADD: PrefabLinks

- Plugin/src/SofaPython3/DataHelper.h
- bindings/SofaExporter/CMakeLists.txt
- bindings/SofaExporter/tests/tests/STLExporter.py
- PrefabLink needed == and != operators
~~- SofaExporter module name has been changed to Exporter to avoid collision with SofaExporter when generated the .lib file. (and all other bindings module does not have Sofa in their names anyway)~~
> Fix compilation with MSVC

- CMakeLists.txt
TODO: uncomment this line in SOFA: https://github.com/sofa-framework/sofa/blob/master/applications/plugins/CMakeLists.txt#L6
> [CMake] Use sofa_add_plugin to make SofaPython3 deactivable

- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.h
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.h
> [Bindings] Fix Vec/Mat template types

- Plugin/CMakeLists.txt
- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonTest.cpp
- Plugin/src/SofaPython3/PythonTest.h
- Plugin/src/SofaPython3/PythonTestExtractor.cpp
- Plugin/src/SofaPython3/PythonTestExtractor.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
- bindings/Sofa/tests/Core/Base.py
- bindings/Sofa/tests/Core/BaseData.py
- bindings/Sofa/tests/Core/BaseLink.py
- bindings/Sofa/tests/Core/BaseObject.py
- bindings/Sofa/tests/Core/Controller.py
- bindings/Sofa/tests/Core/ForceField.py
- bindings/Sofa/tests/PythonModule_Sofa_test.cpp
- bindings/Sofa/tests/Simulation/Node.py
- bindings/SofaRuntime/tests/PythonModule_SofaRuntime_test.cpp
- bindings/SofaTypes/tests/PythonModule_SofaTypes_test.cpp
This PR makes it much more easier to read the output of unittests. It does so by:
- Creating only one python environment for loading the python unittest names (used later on by gtest to allow us to select which tests we want to run). This remove all the crappy info and warning messages from loaded plugins at each python file read.
- Removing useless prints that were bloating the output
- redirecting Python's buffers (stdout and stderr) to the c++ stdout (read by IDEs to classify test outputs). Without this one, the output of the python unittests gets mixed up with each others. This one wasn't easy to find!
Test output **before** this PR:
https://gist.github.com/jnbrunet/7fe9cd97f15a43ba67c7357dd1b929c9
Test output **with** this PR: …
> Cleaner test output

- bindings/SofaExporter/tests/PythonModule_SofaExporter_test.cpp
SofaExporter is disabled by default on out of tree compilations (this is another problem, for another time). Hence I forgot about its tests in  PR #58  . This PR fixes this.
> SofaExporter bindings were still using the old PythonTestList class

- CMakeLists.txt
- SofaPython3 does not inherit some compilation flags from SOFA itself, this would be an issue by itself (here a flag for the maths function are needed with MSVC 🤓)
- Usually, Windows FS does not permit symbolic link so I just copied the files instead for the installation in the user directory
> [FIX/Packaging] Fix MSVC compilation and install in user directory (Windows)

- bindings/Sofa/tests/Core/ForceField.py
- bindings/Sofa/tests/Core/PythonRestShapeForceField.py
@ScheiklP reported a failing test in `PythonRestShapeForceField.py`
```
[ RUN      ] SofaPython3/Sofa.all_tests/62_Sofa_Core_PythonRestShapeForceField_test_example
======================================================================
ERROR: test_example (PythonRestShapeForceField.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
File "PythonRestShapeForceField.py", line 54, in test_example
createScene(Sofa.Core.Node("root"))
File "PythonRestShapeForceField.py", line 42, in createScene
node.addObject("EulerImplicit")
ValueError: Object type EulerImplicit<> was not created  
The object is not in the factory.  
----------------------------------------------------------------------
Ran 1 test in 0.000s
```
This PR should fix it.
> [bindings] Fix missing plugins for forcefield tests

- Plugin/CMakeLists.txt
- Plugin/src/SofaPython3/initModule.cpp
- bindings/BindingsConfig.cmake.in
- bindings/Modules/src/SofaPython3/SofaBaseTopology/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaBaseTopology/Module_SofaBaseTopology.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Components/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Components/Submodule_Components.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Helper/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Helper/Submodule_Helper.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Types/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Types/Submodule_Types.cpp
- bindings/Sofa/tests/Components/Components.py
- bindings/Sofa/tests/Core/ForceField.py
- bindings/Sofa/tests/Core/PythonRestShapeForceField.py
- bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
- bindings/SofaRuntime/CMakeLists.txt
- bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
- bindings/SofaTypes/CMakeLists.txt
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Module_SofaTypes.cpp
Following SOFA's [pluginization](https://github.com/sofa-framework/sofa/issues/1527)  , this PR clean up modules dependencies.
> Fix cmake dependencies

- examples/advanced_timer.py
Title says it all, hope this will help people make use of the power of both python and the advanced time.
> [examples] Add an advanced timer scene demonstration

- examples/basic-addGUI.py
- examples/basic.py
- examples/emptyController.py
- examples/emptyDataEngine.py
- examples/emptyForceField.py
- examples/example-forcefield.py
- examples/liver.py
- examples/loadXMLfromPython.py
Add example to load XML file from python environment
Update scenes further to pluginization
TODO: simple example with matplotlib
> Update examples 202101

- .github/workflows/macos.yml
- CMake/SofaPython3Tools.cmake
Fix an issue on MacOS where the python modules where bundles instead of shared libraries, hence creating a link error during compilation. See https://ci.inria.fr/sofa-ci-dev/job/sofa-custom/CI_CONFIG=mac_clang-3.5,CI_TYPE=release/932/console for the error log.
> [cmake] Fix compilation issue on MacOS

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
Added a binding for `getLookAtFromOrientation` as the complement of `getOrientationFromLookAt`.
> Added a binding for getLookAtFromOrientation

- CMake/SofaPython3Tools.cmake
- CMakeLists.txt
- Plugin/PluginConfig.cmake.in
- SofaPython3Config.cmake.in
- bindings/Modules/src/SofaPython3/SofaBaseTopology/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaDeformable/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Components/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Helper/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Types/CMakeLists.txt
- bindings/SofaExporter/CMakeLists.txt
- bindings/SofaGui/CMakeLists.txt
- bindings/SofaRuntime/CMakeLists.txt
- bindings/SofaTypes/CMakeLists.txt
This PR will allow external projects (SOFA plugins) to use the SP3 cmake macros to set up their bindings.
> [cmake] Export SP3 cmake tools for usage in external projects

- bindings/Modules/src/SofaPython3/SofaBaseTopology/Module_SofaBaseTopology.cpp
Fixes this error:
```
>>> import Sofa.SofaBaseTopology
[ERROR]   [PythonScript] ImportError: dynamic module does not define module export function (PyInit_SofaBaseTopology)
File "<stdin>", line 1, in <module>
```
> [SofaBaseTopology] Fix binding entry point

- Plugin/src/SofaPython3/Prefab.cpp
Fixes https://github.com/sofa-framework/SofaPython3/issues/92
@damienmarchal Could you have a look and let me know if it safe enough to be backported in the v20.12 release?
> [Plugin] Change the initialization order of the Prefab

- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- Plugin/CMakeLists.txt
- Plugin/PluginConfig.cmake.in
- Plugin/src/SofaPython3/PythonEnvironment.h
- Plugin/src/SofaPython3/SceneLoaderPY3.cpp
- bindings/BindingsConfig.cmake.in
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseObject.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PythonScriptEvent.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PythonScriptEvent.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
- bindings/SofaGui/CMakeLists.txt
- bindings/SofaGui/src/SofaPython3/SofaGui/Binding_GUIManager.cpp
- bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
- bindings/SofaRuntime/CMakeLists.txt
- bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Timer/Submodule_Timer.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.h
Coming from breaks with the includes and GUI PR mainly
> [All] Follow sofa master branch

- bindings/Modules/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaGL/Binding_DrawToolGL.cpp
- bindings/Modules/src/SofaPython3/SofaGL/Binding_DrawToolGL.h
- bindings/Modules/src/SofaPython3/SofaGL/Binding_DrawToolGL_doc.h
- bindings/Modules/src/SofaPython3/SofaGL/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaGL/Module_SofaGL.cpp
- examples/additional-examples/pygame_example.py
- examples/additional-examples/pyqt_example.py
I have started the bindings for a Sofa.SofaGL module so that other visualization tools from python can be used (two examples are also added for this). I imagine I should change the naming of the file that I do this bindings in because I started by thinking I need to wrap the drawtool and realized later that I don't need to. I can change the names to whatever you all feel appropriate if this small addition is worth it.
> [SofaGL] Start a Sofa.SofaGL Module

- examples/additional-examples/pygame_example.py
- examples/additional-examples/pyqt_example.py
After an embarassingly long time trouble shooting why a texture wasn't working for me... I thought after finding the problem I should best fix the examples I just uploaded so that it saves other people the same problem.
> [examples] fixed gl initialization in visualization examples

- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
Add a static assert on addCross, if called with something else than Vec2 or Vec3.
Make the code clearer anyway.
> [Bindings/SofaTypes] static_assert on cross()

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseContext.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseMeshTopology.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseMeshTopology.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Topology.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Topology.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
Hopefully this is a better way to fix #113. I don't have the time right now to fill the objects with their class-specific properties/methods, but the groundwork is now there for someone to add them as needed.
The following now works in a python forcefield:
```python
def init(self):
self.topology = self.getContext().getTopology()
self.topology = self.getContext().getMeshTopology()
self.topology = self.getContext().getMeshTopologyLink(Sofa.Core.BaseContext.SearchUp)
print(self.topology.edges.array())
```
> [bindings] Started Topology and BaseMeshTopology bindings

- SofaPython3Config.cmake.in
The cmake configuration file was exporting the value we give to pybind11 (python 3.7) which is the minimum required. Since this value will be later on taken by an external cmake project as a strict version requirement, it will probably fail.
In a nutshell, the problem was:
1. cmake search for 3.7 -> finds 3.9 OK
2. Compilation of SP3 is done using 3.9
3. SofaPython3Config.cmake is exported with a python 3.7 requirement
4. External project is now required to use python 3.7, even tho SP3 was compiled using 3.9
> [cmake] CMake config was exporting the wrong python version

- Plugin/src/SofaPython3/PythonTestExtractor.cpp
- bindings/Modules/tests/main.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseLink.cpp
- bindings/Sofa/tests/Core/BaseLink.py
- bindings/Sofa/tests/PythonModule_Sofa_test.cpp
- bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Timer/Submodule_Timer.cpp
- bindings/SofaRuntime/tests/PythonModule_SofaRuntime_test.cpp
2 functions from Link has been marked as deleted, so those two bindings are not relevant anymore (and does not compile anyway)
> [Bindings] Fix compilation

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseMeshTopology.cpp
Guess I was too quick to say I can't add more bindings to this...
I've just added some getters that are specific to BaseMeshTopology. Mostly so that it is possible to access tetrahedron mesh data when making a custom forcefield.
> [BaseMeshTopology] added getter bindings related to tetrahedrons

- Plugin/CMakeLists.txt
To merge once [#1834](https://github.com/sofa-framework/sofa/pull/1834) is merged
> [Sofa.Testing] Use the Sofa.Testing module if Py3 test is enabled

- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonEnvironment.h
- Plugin/src/SofaPython3/initModule.cpp
- bindings/CMakeLists.txt
- bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
Here are the changes made in SofaPython3 for v20.12
- use new PluginManager callback mechanism introduced in SOFA in https://github.com/sofa-framework/sofa/pull/1777
- use new qt.conf dynamic loading mechanism introduced in SOFA in https://github.com/sofa-framework/sofa/pull/1820
- some RPATH optimization
> v20.12 changes

- Plugin/PluginConfig.cmake.in
This was causing issues when building an external project against SP3.
> [cmake] Fix missing Sofa.Testing in SP3 cmake config file.

- bindings/Sofa/CMakeLists.txt
- bindings/Sofa/package/__init__.py
- bindings/Sofa/tests/CMakeLists.txt
- bindings/Sofa/tests/Core/Base.py
- bindings/Sofa/tests/Core/BaseData.py
- bindings/Sofa/tests/Core/BaseLink.py
- bindings/Sofa/tests/Core/BaseObject.py
- bindings/Sofa/tests/PythonModule_Sofa_test.cpp
- bindings/Sofa/tests/Simulation/Node.py
- bindings/Sofa/tests/Types/Vec3.py
- bindings/Sofa/tests/bench_datacontainer.py
- bindings/Sofa/tests/benchmark.py
- bindings/Sofa/tests/dataaccess.py
When Sofa.Components was activated, its test (bindings/Sofa/tests/Components/Components.py) was the first test executed. 
This test contains a `root.addObject('RequiredPlugin', name='SofaBaseMechanics')`. 
Well, **there is no Python environment cleaning between each test**. 
Thus SP3 tests benefit from the RequiredPlugin done by all the tests executed before.
That is why the deactivation of Sofa.Components made all those tests fail with "cannot create MechanicalObject".
What I did:
- re-enable Sofa.Components (and its test) and move the test to be the last executed
- fix all SP3 tests that use MechanicalObject with some "RequiredPlugin SofaBaseMechanics"
> [tests] FIX all tests using MechanicalObject + Reactivate Sofa.Components

- CMakeLists.txt
Move SofaPython3Tools from `CMake` to `lib/cmake` in build tree.
> [CMake] FIX SofaPython3Tools location in build tree

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
If attribute is not a data or a link, calls the default implementation for __setattr__. This allows to have properties for custom types defined by a user.
> Fix __setattr__

- Plugin/src/SofaPython3/DataHelper.cpp
- Plugin/src/SofaPython3/PythonFactory.cpp
- Plugin/src/SofaPython3/PythonFactory.h
- bindings/Modules/src/SofaPython3/SofaBaseTopology/Binding_SparseGridTopology.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataContainer.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Helper/Binding_Vector.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Types/Binding_BoundingBox.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.h
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Quat.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Quat.h
Title says all.
A prelude to the big PR in SOFA itself.
> Remove use of compatibility layer (Sofa.Compat)

- bindings/Sofa/src/SofaPython3/Sofa/Helper/System/Binding_FileRepository.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Helper/System/Binding_FileRepository_doc.h
- docs/sphinx-stubs/Sofa/Helper/System/__init__.pyi
Needed by https://github.com/sofa-framework/sofa/pull/2198
> [bindings] FIX FileRepository binding (doLowerCaseOnWin32 removal)

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node_doc.h
- bindings/Sofa/tests/Simulation/Node.py
With the current binding it is possible to detect if a node has an object using
the default python hasattr() function. But because of how hasattr() is implement
it imply the generation of the bindinged object regardeless this is usefull or not
from the callee's point of view.
So we add a fast path version, with the corresponding documentation and tests.
> [SofaPython3] Add an hasObject method in Binding_Node to detect if a node has an object.

- CMakeLists.txt
This is needed to fix current error "file not recognized: File format not recognized" on Ubuntu+Clang.
> [CMake] FIX pybind11 finding python

- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- CMakeLists.txt
> [GitHub] Improve workflow for Ubuntu and MacOS

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
> Remove inclusion of a header from Sofa.Compat (again)

- bindings/Modules/src/SofaPython3/SofaGL/Binding_DrawToolGL.cpp
This is a temporary fix to avoid a bad memory leak.
> [SofaGL] Created persistent vparams and drawtool

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_NodeIterator.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_NodeIterator.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node_doc.h
- bindings/Sofa/tests/Simulation/Node.py
The actually implmentation of NodeIterator is broken.
Eg:
- the ```__getitem__``` by name was always returning a BaseObject whatever the iterable was on object, children or parents
- the remove_at method was actually always deleting a Child whatever the iterable was on object, children or parents
There is also no ```__contains__ ```operator which prevent to write pythonic
```python
if "AAA" in node.objects:
pass.
```
This PR:
- fix the broken implementation on remove_at and ```__getitem__``` by adding lambda functions allowing to implement per-type behavior.
- add tests for the fixed features
- implements the ```__contains__``` method and dedicated tests.
- update the corresponding docstring
DRAFTED CODE FROM THE CODE-REVIEW:
```python
def createScene(root):
root.getObjects() #  …
```
> [Binding/Sofa.Core] FIX  Node iterators.

- Plugin/src/SofaPython3/PythonFactory.cpp
- bindings/Sofa/tests/Core/BaseData.py
1) It is not possible to set data's value from string as it was possible in SofaPython2
This PR restore the SofaPython2 behavior to ease the transition process.
But, when using it, a deprecation message is now emitted. 
A test is provided to validate the behavior.
2) Improve the exception returned when trying to set value from an invalid type.
```python
object.name.value = ["Name"]
print(object.name.value)      # is printing '["Name"]'
```
This behavior is not correct and is the consequence of how we set the value for data of type 'string' value. 
In the PR we don't allow this anymore by rising an exception.
```python
object.name.value = ["Name"]
[ERROR]   [SofaPython3::SceneLoader] RuntimeError: trying to set value for 'name' from a python object of type <class 'list'>
```
> [Binding] Improves of the setting of data field of type string.

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- bindings/Sofa/package/__init__.py
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
The existing message:
```console
[DEPRECATED] [DAGNode(root)] The Node.createChild method is deprecated since sofa 19.06.  
To remove this warning message, use 'addChild' instead of 'createChild'.  
```  
Now has the python stacktrace printed:
```console
[DEPRECATED] [DAGNode(root)] The Node.createChild method is deprecated since sofa 19.06.  
To remove this warning message, use 'addChild' instead of 'createChild'.  
At:
controller.py(10): init
```
> [Binding/Sofa.Core]  Add the python call stack to deprecation message.

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.h
Trampoline classes are used to implement sofa components in python.
When used, the default getClassName() (what is showed in the GUI) returns the name of the c++ trampoline class name instead
of the name of the python overrides.
This is why you can see stuff like that in the GUI:
```
Controller_Trampoline(myObject)
ForceField_Trampoline(myFF)
```
This PR change this behavior to retrieve the real class name from python and returns it in getClassName.
So python code like that:
```
class RoboticsController(Sofa.Core.Controller):
pass
```
Will appears with its real name in the GUI:
```
RoboticController(myObject)
```
> [Binding/Sofa.Core] Implement a custom getClassName() for trampoline classes.

- Plugin/src/SofaPython3/PythonFactory.cpp
So now when a PythonFactory actions fails... it provide the filename & line number from where it is emitted.
> [Plugin] Add calling point for the msg_deprecated emitted by PythonFactory;

- Plugin/src/SofaPython3/PythonTest.h
- Plugin/src/SofaPython3/PythonTestExtractor.cpp
No more dependency on boost's libraries (sofa will continue to use header-only lib however)
> Remove usage of boost::filesystem

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonEnvironment.h
Fix #159  by searching the lib/python3/sites_packages directly from:
- SOFA_ROOT if it exists
- the root of SOFA (given by Utils::getSofaPathPrefix), useful when working with build dir (and not setting SOFA_ROOT)
(avoiding the mess of Release/Debug directory in bin)
The total fix for loading SofaPython3, from a build with Windows and MSVC still needs a fix to fix the issue of the .py files dispatched in `<root>/python3/sites_packages` and the .pyd in `<root>/lib/python3/sites_packages` (as reported by #186)
> [Win/MSVC] Fix search of modules

- Plugin/src/SofaPython3/DataHelper.cpp
In SofaPython it was possible do write: 
node.createObject("MechanicalObejct", position=loader.position) 
This was working as loader.position was returning the values of the data field. 
In SofaPython3 ithis will fails as loader.position is not returning anymore the values but the data:
node.createObject("MechanicalObejct", position=loader.position) 
  
Object creation is still using a systematic to-string conversion (see PR #45), so the data are converted to string using the "repr" operator which does not necesserly generate a sofa-compatible string. 
When the object to convert is a BaseData... it is much better to rely on the getValueString() fonction which returns a string compatible with sofa. 
 
> [SofaPython3] Add in DataHelper dedicated to-string conversion from basedata

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonEnvironment.h
Following #190 with a refactoring
> [Plugin] Refactor PythonEnvironment init

- CMakeLists.txt
- splib/__init__.py
In initial version of SofaPython3 there was a partial version of SPLIB that was removed. 
If someone still do an import splib expecting to rely on the one in SofaPython3 it will get and error saying splib is missing.
In this PR we have added a fake splib file so importing it results in an exception indicating how to install it.
> [SofaPython3/splib] Add a gentle deprecation message and info on how to find the SPLIB.

- Plugin/src/SofaPython3/PythonEnvironment.h
"Hack" to force to link with the release version of python3x.lib
The link command is contained deep in python (pyconfig.h):
```
/* For an MSVC DLL, we can nominate the .lib files used by extensions */
#ifdef MS_COREDLL
/* not building the core - must be an ext */
/* So MSVC users need not specify the .lib
file in their Makefile (other compilers are
generally taken care of by distutils.) */
#endif /* MS_COREDLL */
```
So according to various sources, the "best" way is to disable debug before including python.h
https://bugs.python.org/issue22411
> [MSVC] Fix link error in debug configuration

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
The current exception handler in the DataEngine binding is misleading as it
convert every exceptions into one saying:
"The DataEngine requires an update method with no parameter and no return type"
This is wrong. 
It is better to let the original exception propagate.
> [Sofa.Core.Binding] Remove suprious exception handler in Binding_DataEngine

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
Currently it is possible to set a parent by calling:
```python
oneData.setParent(otherData) 
```
With the PR it become possible to do 
```python
oneData.setParent("@/myobjcet.data") 
```
It is questionnable wether we want such behavior or not, but as long as lazy-string link making is allowed in Sofa.core it make sense to have it in the binding.
> [Sofa.Core.BaseData] Add to the binding a method BaseData::setParent from a link path

- .github/workflows/ci.yml
Tags named as branches are not very helpful since they create usage conflicts and force the user to specify what he wants to manipulate between `refs/tags/something` (the tag) or `refs/heads/something` (the branch).
> [CI] FIX release tag name (do not use branch name)

- Plugin/src/SofaPython3/PythonFactory.cpp
- Plugin/src/SofaPython3/config.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Prefab.cpp
Since the version 2.8.1, pybind is doing the binding on attributeError automatically.
(https://github.com/pybind/pybind11/commit/78ee782bd494debcbc166f717379a4f9c2093c0f)
It will be throw a compilation error in SofaPython3 because it was also bind here and there (`already defined` error)
This PR creates a macro (to avoid copy-paste) which, according to the version of pybind, bind or not the attribute_error.
I am also wondering if it was really necessary to do it in each binding_module (and PythonFactory.cpp) and why not once for all in the PythonFactory.h ?
> Fix for pybind version >= 2.8.1

- bindings/Sofa/tests/Simulation/Simulation.py
- examples/loadXMLfromPython.py
On Windows, the created temp file is not accessible for SOFA (therefore fails while trying to load the XML file), as it is being opened by the current process.
We just need to close it before giving it to Sofa.Simulation.init().
EDIT: same problem with loadXMLFromPython (in examples)
EDIT2: Fix #214
> [Test] Fix Simulation.py test

- Plugin/src/SofaPython3/PythonTest.cpp
- Plugin/src/SofaPython3/PythonTest.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.cpp
Some deprecated testing headers are used, so this PR change those to the normal ones.
(those headers will be disabled in a PR in SOFA, before v21.12 release)
> [Plugin] Use non-deprecated header/class

- Plugin/src/SofaPython3/config.h
Fix test introduced on pybind version in #216 
It was failing with version v2.9.0.
Introduced a new macro to test the version against, easier to read and less error-prone.
> Fix test on pybind version

- bindings/Sofa/package/__init__.py
On linux (and mac) the process to guess SOFA_ROOT only print it but does not do anything with it...
So this PR set this value (while python is running) so Sofa under python can find its .so if SOFA_ROOT is not set.
~~(and set SOFAPYTHON3_ROOT as well but I dont know the use of this one)~~
> Set SOFA_ROOT if not set and successfully guessed

- .github/workflows/ci.yml
Now that the parameter `sofa_scope` of https://github.com/sofa-framework/sofa-setup-action is on 'standard' by default, we must force it to 'minimal' because SOFA 'standard' contains SP3 binaries.
> [CI] Force SOFA scope to 'minimal'

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
For https://github.com/sofa-framework/sofa/pull/2773
> Restore xml and python different naming conventions

- bindings/Sofa/tests/Core/BaseObject.py
To merge in the same time as https://github.com/sofa-framework/sofa/pull/2766
> [Binding/Sofa.Core] Update MechanicalObject Target in test 

- Plugin/src/SofaPython3/DataHelper.cpp
The problem in issue #2761 is related to how we get the raw pointer from sofa to python numpy array. 
If the data is dirty then the pointer was not the right one. 
Can you try it fix the issue 
@AlbanOdot @jnbrunet @fredroy ?
Fix https://github.com/sofa-framework/sofa/issues/2761
> [SofaPython3/Binding] Do not use the binding cache mecanisme when the data is dirty (Fix sofa issue #2761)

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
The object created from python needs special care to avoid being deleted by the python garbage collection mecanisme.
In #74 and #75 the smart pointer mecanism was refactored. The refactoring added a py::keep_alive, in addObject but didn't in other functions like addChild and createObject/createChild.
Not havin this has the consequence that the python side of c++ object is gc'ed. 
The PR adds the missing ones.  
Fix #245
> [SofaaPython/Binding] Add py::keep_alive in Binding_Node.cpp (FIX issue #245)

- Plugin/CMakeLists.txt
- Plugin/src/SofaPython3/DataCache.h
- Plugin/src/SofaPython3/PythonEnvironment.h
- Plugin/src/SofaPython3/PythonFactory.h
- Plugin/src/SofaPython3/SceneLoaderPY3.h
- Plugin/src/SofaPython3/config.h
- Plugin/src/SofaPython3/config.h.in
- Plugin/src/SofaPython3/initModule.cpp
fixes #235 
Building SofaPython3 with the master version of pybind11 (or any "non-release" version with a patch tag in PYBIND11_VERSION_PATCH) will cause a compile error, because the PYBIND11_SOFA_VERSION macro definition expects a number-only macro.
There are two solutions to this issue:
1. is the one I'm proposing in this PR: removing the patch number from PYBIND11_SOFA_VERSION. I don't think it is necessary in SOFA to know the patch version of pybind11, but I might be wrong...
2. updating the documentation for SofaPython3, to explicitly tell people to either install pybind11 from their system package manager, or tell them to checkout a release version of pybind11 if one wants to build it from its source repository.
> FIX PYBIND11_SOFA_VERSION

- Plugin/src/SofaPython3/PythonEnvironment.cpp
it is important when reloading a scene to force python to reload all the loaded modules to be sure the context is as clean as possible.
This PR restore this mechanism and clean the duplicated code from between SofaRuntime and Sofa
> [SofaPython3/Plugin] Restore the automatic reload of modules

- Plugin/src/SofaPython3/PythonEnvironment.cpp
The python3 mecanisme used in place of python2's on is not handling pyscn by default.
Declaring .pyscn in the list of sources suffix is needed to make that possible.
@guparan can you review and merge plz ?
> [SofaPython3] Fix regression introduced in #PR182

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.cpp
It is often useful to be able to see what kind of events are received by a controller.
This PR add this behavior by printing the message name and parameters in the console when the 'printLog'  data is checked.
```console
[INFO]    [MyController(TOTO)] onUpdateMappingEndEvent {'type': 'UpdateMappingEndEvent', 'isHandled': False}
[INFO]    [MyController(TOTO)] onAnimateBeginEvent {'type': 'AnimateBeginEvent', 'isHandled': False, 'dt': 0.01}
[INFO]    [MyController(TOTO)] onAnimateEndEvent {'type': 'AnimateEndEvent', 'isHandled': False, 'dt': 0.01}
[INFO]    [MyController(TOTO)] onUpdateMappingEndEvent {'type': 'UpdateMappingEndEvent', 'isHandled': False}
> [Sofa.Core] Print the event when printLog is activated.

- bindings/CMakeLists.txt
- bindings/Sofa/CMakeLists.txt
Reverts sofa-framework/SofaPython3#269
Due to old version of cmake which does not handle setting the folder property on INTERFACE_LIBRARY
```
CMake Error in applications/plugins/SofaPython3/bindings/Modules/CMakeLists.txt:
INTERFACE_LIBRARY targets may only have whitelisted properties.  The
property "FOLDER" is not allowed. 
```
(output from a old version of cmake)
> Revert "Organize targets into Bindings folder"

- Plugin/src/SofaPython3/DataHelper.h
While doing https://github.com/sofa-framework/sofa/pull/3031 , I stumbled on a type error.
It seems that python3 <=3.9 was defining ssize_t for MSVC, but not on python3.10 anymore (my guess after few searches).
And obviously, I was on python3.10  🌝 
Hence thats why it is compiling on the CI but not on my system :lucky:
> [Plugin] Fix compilation for msvc and python 3.10

- bindings/Sofa/Bindings.SofaConfig.cmake.in
Needed to configure any project with a dependency on SofaPython3.
> [CMake] FIX missing find_package in Config

- Plugin/src/SofaPython3/DataHelper.cpp
To fix memory error in PR #243 there is the need to get the latest data by calling getValue().
The way it was done in the 243 PR is wrong because it is using a begin/end edit pairs which trigger the DDG's followers (and not only precessors) which in return notify that the data is not eddited anymoer (while it was not editted at all). The consequence was that every call on read access on the python side eg: print(myobject.position.value)
was triggering the data change mecanisme to the position's follower.
> [SofaPyhon3/Plugin] Fix regression introduced in PR #243

- bindings/Sofa/package/prefab.py
Replace Sofa.Prefab "properties" by "prefabParameter" & "prefabData"
The use of existing properties are not clear as useres tend to put both data & prefab properties (which trigger the update)
To clarify that we split properties in two... one called prefabParameter and the other prefabData.
A deprecation message is introduced when usnig "properties"
> [Sofa.Prefab] Replace Sofa.Prefab "properties"

- bindings/BindingsConfig.cmake.in
Because SofaLinearSolver is in module. And when imported this fails prevent to compile plugins that rely on SofaPython3.
> [FIX] Remove SofaLinearSolver in BindingsConfig.cmake.in

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/SceneLoaderPY3.cpp
- bindings/Sofa/package/prefab.py
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
In runSofa, 
it is possible to get where the object has been instanciated in the scene from the scenegraph. This was working in both python2 and xml. 
This was broken with SofaPython3 so the "Go Scene" popup menu entry is always grayed out.  
The PR restore the behavior. 
NB: for complex python scene it would be better to have the full creation stack instead of just the last line... but this may be an interesting UX improvement but outside of the scope of this PR.
> [FIX] The callpoint api is broken since SofaPython3. 

- bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
ifdef's were relying on the old naming
(so qt.conf was not read, and windows could not load sofa.gui with qt)
> [Sofa.Gui] Fix macro to enable qt.conf

- Plugin/src/SofaPython3/Prefab.h
So the string returned is now "Prefab" instead of "Node"
Which leads to clearly show in GUIs the fact it is a prefab and not a simple Node.
> [SofaPython3/Plugin] Add GetCustomClassName to Prefab

- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonEnvironment.h
The execution of SOFA from a python3 environement is not working anymore because
some features need Sofa & SofaRuntime modules to be loaded but the loading is done when
initializing only in the embeded python interpreter.
To fix this, the PR move the module loading and access into its own singleton that initialize at
first use.
Fixing that is important for 22.06 release.
For the future, refactoring the PythonEnvironment file to split PythonEnvironment in two, to separate what is actually relevant for the PythonEnvironment and what
should be part something like PythonEmbededInterpreter.
Fix #283
> [SofaPython3] Separates the pre-loaded python modules out of the python (Fix issue #283)

- Plugin/src/SofaPython3/PythonEnvironment.cpp
This line: https://github.com/sofa-framework/SofaPython3/blob/master/Plugin/src/SofaPython3/PythonEnvironment.cpp#L255
is not working as expected with an installed SofaPython3 on Windows.
We want PythonEnvironment to auto-add SofaPython3's site-packages but on Windows the SofaPython3.dll is copied in bin (for dependency finding reasons), leading addPythonModulePathsFromPlugin to fail finding SofaPython3's site-packages.
I added another way of searching, keeping the old way as fallback.
> [Plugin] FIX environment init on Windows install

- Plugin/CMakeLists.txt
- Plugin/src/SofaPython3/DataHelper.cpp
- Plugin/src/SofaPython3/LinkPath.cpp
- Plugin/src/SofaPython3/LinkPath.h
- Plugin/src/SofaPython3/PythonFactory.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_LinkPath.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_LinkPath.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_LinkPath_doc.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
- bindings/Sofa/tests/Core/Base.py
- bindings/Sofa/tests/Core/BaseData.py
This PR is following the discussion in #197 
The existing syntax to make links in SofaPython3 is the following one:
```python
node.addObject("MeshObjLoader", name="loader")
node.addObject("MechanicalObject", position=node.loader.position.getLinkPath())
```
In addition to be very verbose the getLinkPath() is returning a string (eg: "@/node/loader.position").
Representing linkpath with string has the drawback of forcing the two objects to be part of the same simulation graph which is not always the case.
Example of code that does not work as expected:
```python
def MyPrefab(target):
node = Sofa.Core.Node("MyPrefab")
node.addObject("MeshObjLoader", name="loader")
node2.addObject("MechanicalObject", position=target)
return node
def createScene(root):
root.addObject("MeshObjLoader", …
```
> [SofaPython3] Add a LinkPath object in both the binding and plugin.

- bindings/Sofa/tests/CMakeLists.txt
- bindings/Sofa/tests/Core/BuildConstraintSystemEndEvent.py
- bindings/Sofa/tests/Core/Events.py
- examples/access_compliance_matrix.py
This PR implements unit tests for PR #3418 from SOFA.
The example _access_compliance_matrix_ is extended through using the two new types of event, **BuildConstraintSystemEndEvent** and **SolveConstraintSystemEndEvent**.
> [Example/Tests] Add events in the constraint solver pipeline

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseMeshTopology.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PointSetTopologyModifier.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PointSetTopologyModifier.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
- examples/pointSetTopologyModifier.py
I want to add bindings for `PointSetTopologyModifier`'s `addPoints` and `removePoints` in order to change the size of a `PointSetTopologyContainer` that are propagated to components that are linked with the container (e.g. `MechanicalObject`, `RestShapeSpringsForceField`, `FixedConstraint`, ...).
Work in Progress, because the binding does not work as expected and I could use some help on that.
I added an example in https://github.com/ScheiklP/SofaPython3/blob/point_topology_modifier/examples/pointSetTopologyModifier.py
On first call, `addPoints` works as expected, every call after that does not. `removePoints` works well, but validity of point to be removed is not checked yet. Should `renumber` also be called?
https://user-images.githubusercontent.com/29635054/180652221-76295c4d-7b2c-4e59- …
> [Binding/Sofa.Core] PointSetTopologyModifier

- Plugin/src/SofaPython3/DataHelper.cpp
When accessing a data vector through Python scripting, the `py::buffer_info` structure returned by the `toBufferInfo` method contains a pointer to the vector data buffer. By default this pointer is retrieved thanks to SOFA's `getValuePtr` method, which in the end returns a reference to the vector's first element (`&data[0]` cf in _VectorTypeInfo.h_). This leads to an undefined behaviour when the data vector is empty (i.e.: data[0] doesn't exist).
This PR adds a safeguard in _DataHelper_, checking the size of the vector before calling `getValuePtr`. If the vector is empty (size = 0), we pass a null pointer to the final `py::buffer_info` structure.
As I'm not fully aware of the consequences of this change, this PR is also open to discussion.
NB: a different PR is open in SOFA …
> [DataHelper] Change default access of vector data buffer 

- Plugin/src/SofaPython3/DataHelper.cpp
- Plugin/src/SofaPython3/DataHelper.h
- bindings/Sofa/tests/Core/BaseData.py
The issue 313 shows that the memcache is not updated when the data have changed but the flag is not anymore dirty. This happens when between the change and the call to the writeable() function somewhere else in Sofa, a component/controller/the gui had called the updateIfDirty() method. 
In order to detect the "no more dirty but changed data" a counter is added to the memcache enties so we can detect if it is different from the counter stored in the BaseData. 
fix issue #313 
The PR also restore all the tests in Base.py  that are failing silently since a long time (the fact that parse error in python tests can get un-noticed is very problematic, we should fix that one day.).
> Add a counter to memcach so that we can detect data change

- Plugin/CMakeLists.txt
- Plugin/src/SofaPython3/SpellingSuggestionHelper.h
- Plugin/src/SofaPython3/config.h.in
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Same as #314 but with 2.6.0 setting for the backward compatibility to old pybind11 version.
py::type was introduced at 2.6.0 so there is no need for the macro after that.
The previous merged problem was not detected before because pybind11 on sofa-jenkins is 2.6.2 while pybind11 on sofapython/github actions is 2.4.
> Add addObject spelling support (again)

- .github/workflows/ci.yml
API with SOFA v22.06 had been not compatible for a long time now
> Remove v22.06 for the CI

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Mass.cpp
This is a fix for https://github.com/sofa-framework/BeamAdapter/discussions/86
The call of `assembleKMatrix` leads to a UB without the suggested change.
> Fix: mass binding is defined to have multiple inheritance

- bindings/Sofa/tests/Core/Mass.py
The multiple inheritance property of Mass has been identified problematic in a previous pull request #325.
The test in this commit succeeds if Mass is defined with the label py::multiple_inheritance(). Otherwise it crashes.
> Add unit test for Mass multiple inheritance

- docs/sphinx/source/index.rst
- docs/sphinx/source/menu/SofaPlugin.rst
This PR proposes two main changes in the doc:
- update the required python version (3.7 -> 3.8)
- improve the source files of the '*Using the plugin*' section describing the python API and script format to use SOFA within python
The actual files read by readthedoc are not updated and we should rethink about the doc generation.
@marques-bruno : sorry to poke you but I tried to follow the [instructions to build the readthedoc files](https://github.com/sofa-framework/SofaPython3/tree/master/docs#2-generating-the-stubs) but it failed.
The command : `pybind11-stubgen -o sphinx-stubs --no-setup-py --ignore-invalid=signature --root-module-suffix="" Sofa`
gives the following error:
```
[ERROR]   [PythonScript] TypeError: 'Sofa.Components.Creator' object is not iterable
File …
```
> [doc] Update SofaPython3 plugin documentation

- bindings/SofaGui/Bindings.SofaGuiConfig.cmake.in
- bindings/SofaGui/CMakeLists.txt
- bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
due to the fact that SofaGui is only included with the compat layer now.
(due to https://github.com/sofa-framework/sofa/pull/3550)
The cmake file will now explicitly find/add the different guis now (instead of implicitly with the  former SofaGui)
> [Bindings.SofaGui] Fix compilation without compat layer

- CMakeLists.txt
- Plugin/CMakeLists.txt
- Testing/CMakeLists.txt
- Testing/SofaPython3TestingConfig.cmake.in
- Testing/src/SofaPython3Testing/PythonTest.cpp
- Testing/src/SofaPython3Testing/PythonTest.h
- Testing/src/SofaPython3Testing/PythonTestExtractor.cpp
- Testing/src/SofaPython3Testing/PythonTestExtractor.h
- Testing/src/SofaPython3Testing/config.h.in
- Testing/src/SofaPython3Testing/init.cpp
- bindings/Modules/tests/CMakeLists.txt
- bindings/Modules/tests/main.cpp
- bindings/Sofa/tests/CMakeLists.txt
- bindings/Sofa/tests/PythonModule_Sofa_test.cpp
- bindings/SofaRuntime/tests/CMakeLists.txt
- bindings/SofaRuntime/tests/PythonModule_SofaRuntime_test.cpp
- bindings/SofaTypes/tests/CMakeLists.txt
To me, it is weird that the testing features were included in the SofaPython3 lib. It was optionally compiled (based on the value of `SP3_BUILD_TEST`), and it comes with all its dependencies (`Sofa.Testing`, gtest etc). That's why I created a dedicated module
> Extract testing features from the main library

- bindings/Sofa/package/__init__.py
The script relied on finding `Sofa.Helper.dll` in `sofa_root/bin`. But MSVC deals with multiple compilation modes. It adds another folder under `sofa_root/bin`. This was not taken into account. The new script now searches `Sofa.Helper.dll` in compilation folders.
Note that it is not necessary for installed package since the compilation mode folder does not exist.
Also note that it is not possible to select the compilation mode. The first found is selected.
> Support dev environments on Windows

- Plugin/src/SofaPython3/SceneLoaderPY3.cpp
- Plugin/src/SofaPython3/SceneLoaderPY3.h
Follows https://github.com/sofa-framework/sofa/pull/3799
Allows to format the warning message such as:
```
[WARNING] [SceneCheckMissingRequiredPlugin] This scene is using component defined in plugins but is not importing the required plugins.  
Your scene may not work on a sofa environment with different pre-loaded plugins.  
To fix your scene and remove this warning you just need to cut & paste the following lines at the beginning of your scene:   
root.addObject('RequiredPlugin', name='Sofa.Component.AnimationLoop') # Needed to use components [FreeMotionAnimationLoop]  
root.addObject('RequiredPlugin', name='Sofa.Component.Collision.Detection.Algorithm') # Needed to use components [BVHNarrowPhase,BruteForceBroadPhase,BruteForceDetection,CollisionPipeline] …
```
> Add syntaxForAddingRequiredPlugin function

- Plugin/src/SofaPython3/PythonEnvironment.cpp
and deprecate it in favor of SOFAPYTHON3_PLUGINS_PATH to be more consistent with the other names.
Use `system::FileRepository` instead of manually handle the content of the env var.
Especially that it was not handling the correct separating marker for Windows (which is ";" instead of ":" apparently)
**PLUS**
Added a message when the path given to `addPythonModulePath` is not correct.
This actually happens often, e.g BeamAdapter/Cosserat did not update their cmake config when the python3 was renamed.
With Cosserat you get `Added 'D:/sofa/src/plugins/CosseratPlugin/python' to sys.path` even if the directory does not exist.
> Fix SOFAPYTHON_PLUGINS_PATH env var with Windows (and add a warning error)

- CMake/SofaPython3Tools.cmake
The command `configure_file` with attribute `@ONLY` does not make sense for binary files. Actually, it corrupts them when copying them. So they have to be handled differently.
I don' t know how to detect that a file is binary or not, so I adopted a strategy where I checked if the file extension matches a list of known extensions. This is not generic...
For the record, we have binary files in Python modules in SoftRobots. It corresponds to meshes. The Finger for example
> Support copy of some binary files

- .github/workflows/ci.yml
#363 broke the _Deploy artifact_ action as MacOS is removed from CI.
This did not appear at the PR CI as this action is not launched from open PR.
> Fix deploy artifacts as MacOS is temporarily disabled.

- .github/workflows/ci.yml
Propagate #367 (for `v23.06`) into `master`.
The `softprops/action-gh-release` Github action used in the CI to deploy assets was incorrectly configured to the `master` branch (default behavior), instead of the current release set by the `sofa_branch` field in the `build-and-test` matrix.
This lead to the following undesired behavior:
- source code archives (zip and tar) were generated from master branch instead of release branch. Other assets (releases for Windows, Linux and MacOS) were generated from correct branch.
- release tag pushed by this action (tag in the form `release-<version>`) was incorrectly set to `master` branch, which is invalid when current release is not `master` (such as `v<version>`)
> Fix softprops/action-gh-release source from master to release branch

- .github/workflows/ci.yml
The `softprops/action-gh-release` Github action used in the CI to deploy assets was incorrectly configured to the `master` branch (default behavior), instead of the current release set by the `sofa_branch` field in the `build-and-test` matrix.
This lead to the following undesired behavior:
- source code archives (zip and tar) were generated from master branch instead of release branch. Other assets (releases for Windows, Linux and MacOS) were generated from correct branch.
- release tag pushed by this action (tag in the form `release-<version>`) was incorrectly set to `master` branch, which is invalid when current release is not `master` (such as `v<version>`)
> Fix 23.06 wrong assets source

- bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Timer/Submodule_Timer.cpp
- examples/advanced_timer.py
The timers labels changed
The changes in file `Submodule_Timer.cpp` are only formatting.
I also reduced the number of elements in the scene and specified the required plugins
> Follow changes from #3959

- Plugin/src/SofaPython3/initModule.cpp
- Plugin/src/SofaPython3/initModule.h
The entrypoint of the plugin SofaPython3 could not be called from somewhere else, for example to force-load the library (dll).
> [Plugin] Add a public function init() to allow loading the plugin statically

- examples/additional-examples/ControllerScene.py
- examples/additional-examples/pygame_example.py
- examples/additional-examples/pyqt_example.py
- examples/emptyController.py
- examples/emptyDataEngine.py
- examples/example-forcefield.py
- examples/liver.py
> [Examples] Remove usage of deprecated plugins

- bindings/Modules/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaLinearSystem/Binding_LinearSystem.cpp
- bindings/Modules/src/SofaPython3/SofaLinearSystem/Binding_LinearSystem.h
- bindings/Modules/src/SofaPython3/SofaLinearSystem/Binding_LinearSystem_doc.h
- bindings/Modules/src/SofaPython3/SofaLinearSystem/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaLinearSystem/Module_SofaLinearSystem.cpp
- examples/access_mass_matrix.py
The bindings are very similar to the ones in SofaLinearSolver, but they can act on a LinearSystem. It is needed when accessing a LinearSystem which is not the one used by a LinearSolver, as in the provided example
> Introduce bindings to linear system

- SofaPython3Config.cmake.in
Add EXACT to find_package of python because version should not mismatch
> Fix out-of-tree compilation of dependencies

- CMakeLists.txt
- SofaPython3Config.cmake.in
This pr aims at filtering the version put in the config file to only force the major and minor version. Allowing to work even with different patches
> fix Versioning to allow patches

- Plugin/src/SofaPython3/PythonEnvironment.cpp
The current test was doing the opposite of what was intended 💩
> [Environment] Fix test for plugins envvars 

- Plugin/src/SofaPython3/SceneLoaderPY3.cpp
Currently DeprecationWarning exception risen by python code are reported as  msg_error() 
which is misleading. The PR detect it so it is reported with msg_deprecated() 
This is the source of this: 
https://github.com/SofaDefrost/STLIB/pull/117
> [SceneLoader] Add a special error message handler for DeprecationWarning

- bindings/Sofa/package/livecoding.py
https://docs.python.org/dev/whatsnew/3.12.html#imp
Imp has been deprecated since Python3 3.4 (!) and has been removed in 3.12.1
Hitting first macOS users because homebrew recently updated their version.
More context : https://discuss.python.org/t/how-do-i-migrate-from-imp/27885/13
---
`livecoding.py` is called in PythonEnvironment, so it is throwing an error every time.
This PR replaces imp by importlib.
I just tested by calling directly the file (and using the onReimpAFile(file).
There is no test at all currently and this onReimpAFile() function is only used for prefab.
Fix partially https://github.com/sofa-framework/sofa/discussions/4624
> Replace deprecated imp by importlib

- Testing/src/SofaPython3Testing/PythonTest.h
This solves the following error, which is produced with GCC 7 due to the fact that std::filesystem is an experimental feature.
```
[ 98%] Building CXX object external_directories/SofaPython3/Testing/CMakeFiles/SofaPython3Testing.dir/src/SofaPython3Testing/PythonTest.cpp.o
In file included from /home/rafael/src/Slicer-SOFA-gcc7/Release/SofaPython3/Testing/src/SofaPython3Testing/PythonTestExtractor.h:22:0,
from /home/rafael/src/Slicer-SOFA-gcc7/Release/SofaPython3/Testing/src/SofaPython3Testing/PythonTest.cpp:38:
/home/rafael/src/Slicer-SOFA-gcc7/Release/SofaPython3/Testing/src/SofaPython3Testing/PythonTest.h:28:12: error: ‘std::filesystem’ has not been declared
using std::filesystem::path;
^~~~~~~~~~
/home/rafael/src/Slicer-SOFA-gcc7/Release/SofaPython3/Testing/src/SofaPython3Testing/Python …
```
>  [Slicer-SOFA integration] Add compatibility with GCC

- bindings/Sofa/package/__init__.py
Debug DLLs were never searched because they have a suffix that was not taken into account.
> Support for Debug DLLs

- .github/workflows/ci.yml
- bindings/Sofa/package/__init__.py
Title.
Sometimes it is frustrating with MSVC config that python3 interpreter choose a bad build directory for SOFA_ROOT because he just find the first build directory with Sofa.Helper.dll. So if you have both Release and RelWithDebInfo, it will always choose the first one, even if you are currenty working with the second one.
So this PR introduces a new envvar to force choose a configuration, called `SOFA_BUILD_CONFIGURATION`.
Actually it can also be useful if a user uses a custom name for the configuration type (other than release, relwithdebinfo, etc)
Note that this feature would be useful for macOS/XCode but for the moment SofaPython3 always considered macOS like Linux/{makefile/ninja}, i.e with a single configuration mode.
> Add new env.var to set a build configuration at runtime

- Plugin/src/SofaPython3/PythonEnvironment.cpp
The GIL is initialized by `Py_Initialize()` since Python 3.7 (called earlier)
> Update PythonEnvironment regarding GIL deprecation

- Plugin/src/SofaPython3/SceneLoaderPY3.cpp
When using a wrong attribute to an object,  the error message is printed with a "Deprecation" status 
```
[DEPRECATED] [SofaPython3::SceneLoader] Unable to completely load the scene from file '/Users/fred/Work/sofa/SofaLnRobotics/scenes/demos/Demo_05_simple_data_inverse.py'.
Python exception:
AttributeError: Unable to find attribute: EdgeSetTopologyContainer
You possibly wanted to access:
- The object named 'EdgeSetTopologyModifier' (80% match)
```
it seems that the "AttributeError" exception from pybind is also a "DeprecationWarning" apparently ?? 🤔 (according to the test)
so this PR tests if the exception is a DeprecationWarning and NOT an AttributeError  to display as "deprecated"
Result:
```
[ERROR]   [SofaPython3::SceneLoader] Unable to completely load the scene from file …
```
> Display attribute_error with msg_error

- .github/workflows/ci.yml
- Plugin/src/SofaPython3/DataHelper.cpp
- Plugin/src/SofaPython3/DataHelper.h
- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonEnvironment.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Helper/Submodule_Helper.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
- bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
Was
A small experiment (successful?) about unloading module when they themselves are unloaded~~
Also should help fix the shenanigans about #425 and https://github.com/sofa-framework/sofa/pull/4828
This PR:
- Fix #429 
- #425 
- in Windows/MSVC, fix quitting when using python3 as interpreter
output before:
```shell
$ python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import Sofa
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: D:\sofa\build\current
Warning: environment variable SOFAPYTHON3_ROOT is empty. Trying to guess it.
Guessed SOFAPYTHON3_ROOT: D:\sofa\build\current
Detected SOFA development …
```
> [Bindings] Remove static SofaInitializer, call unload into each respective module and clear cache

- CMakeLists.txt
- bindings/CMakeLists.txt
- bindings/SofaGui/CMakeLists.txt
Based on 
- #409 
Title says all.
IMO, we should never load Sofa.Gui.Qt and Sofa.Gui.QglViewer implicitly and do similarly to runSOFA, aka load the modules on demand (like Sofa.ImGui). 
But this PR is behaviorally(?) compatible with current scenes and binaries: if you dont switch-off the dependant options, it will still be implicitly loaded.
> [Sofa.Gui] Add dependant option to not bind qt/qglviewer to Sofa.Gui (even if present)

- Plugin/src/SofaPython3/PythonEnvironment.cpp
runSofa + SofaPython3 is crashing when quitting (since I dont know when) ?
After investigation, PyMem_Free is called without GIL, which is illegal.
https://github.com/python/cpython/issues/105690
I guess this behavior started when clearing the env when unloading (https://github.com/sofa-framework/SofaPython3/pull/432), plus python 3.12
Instead we must call `PyMem_RawFree` which allows us to delete non-obj (our case) without the gil.
PS1: the whole PySys_SetArgvEx stuff is deprecated and will need  a rewrite.
PS2: I am skeptical about the needs to store the m_argv, etc 🤔
> Use PyMem_RawFree when resetting PythonEnvironmentData

- Testing/src/SofaPython3Testing/PythonTest.cpp
- Testing/src/SofaPython3Testing/PythonTestExtractor.cpp
- bindings/Sofa/package/__init__.py
- bindings/Sofa/tests/Core/Mass.py
- examples/import_python_scene.py
Feature 1: 
Currently when loading unittest (for python) into gtest (c++), a failure while loading the test in python does not generates a test failure which is problematic as load time error will be unnoticed.
The PR transform the loading of a python file containing unittest as real test in the gtest framework. The consequence is that a failure to load the file is not more ignored but reported as a gtest failure in the following way:
Feature 2:
Adds method import_sofa_python_scene(path_to_scene : str) in the python package Sofa
The introduced method loads dynamically python module containing a scene and returns it.    
This allows to do:
```python
scene = import_sofa_python_scene("myscene.py")
root = scene.createScene(Sofa.Core.Node("root"))
...
root.addObject(....)
```
> Add two testing features 

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ObjectFactory.cpp
NB: this makes subgen fails because of an  "empty" name.
> Fix missing name in ClassEntry Binding_ObjectFactory.cpp

- examples/access_constraint_matrix.py
Apparently MeshMatrixMass with Lumping is not equivalent with DiagonalMass 🫢
> [Scene] Partial revert of PR459

- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation_doc.h
Not sure why it was not here before 🤔
as initRoot(root) does different things than init(root)
On my side using directly python with imgui (on macos), this fixes the rendering at startup (as the bbox is not computed initially without initRoot).
Actually, all the scenes which are run using directly python should use initRoot (to be consistent with runSofa)
> [Simulation] Add initRoot binding

- docs/sphinx/source/content/Installation.rst
- Fix typo Ubuntu -> MacOS
- Update all 3.8 to 3.10 python version
> [doc] Update Installation.rst

- examples/ReadTheDocs_Example.py
- examples/additional-examples/ControllerScene.py
- examples/additional-examples/pygame_example.py
- examples/additional-examples/pyqt_example.py
- examples/advanced_timer.py
- examples/basic-addGUI.py
- examples/basic.py
- examples/emptyController.py
- examples/emptyDataEngine.py
- examples/emptyForceField.py
- examples/example-forcefield.py
- examples/liver-scriptcontroller.py
- examples/liver.py
- examples/loadXMLfromPython.py
- examples/springForceField.py
- examples/taskScheduler.py
Since https://github.com/sofa-framework/SofaPython3/pull/457, the `init()` function does not trigger the `computeBbox`. The `initRoot()` does it since it is a specific initialization for the root node.
See typical discussion: https://github.com/sofa-framework/sofa/discussions/5174
> [examples] Use initRoot instead of init

- bindings/Sofa/Bindings.SofaConfig.cmake.in
As suggested by @alxbilger in https://github.com/SofaDefrost/SoftRobots.Inverse/pull/53 , thanks for the fix.
This adds the missing dependency to `Sofa.SimpleApi` for `Bindings.Sofa` cmake config file.
I'm waiting the conda CI to validate it fixes the problem on `SoftRobots.Inverse` and will mark as ready to review if succeeds.
> Fix bindings cmake config for missing simpleApi

- splib/core/enum_types.py
- splib/mechanics/collision_model.py
- splib/mechanics/hyperelasticity.py
- splib/mechanics/linear_elasticity.py
- splib/topology/dynamic.py
- stlib/geometry/__geometry__.py
- stlib/geometry/extract.py
- stlib/geometry/file.py
- stlib/prefabs/collision.py
- stlib/prefabs/visual.py
Minor cleaning while testing:
- `ElementType`: consistance with `POINTS`, `EDGES`, `TRIANGLES` which are in plurals 
- ~~`addCollisionModel`: I think that the `TRIANGLES` type should also add points and lines CollisionModel, same for `LINES`~~
- `destElemType`, `fromElemType` to `destElementType` and `fromElementType`: we already use a lot the word `Element`, I vote to avoid this renaming (abbreviation)
- `CollisionParameters`: I think the parameters `proximity`, `contactStiffness`, `contactFriction`, `spheresRadius` are expert/advanced parameters and should not be exposed.
> [stlib-splib] work on prefabs: cleaning

- docs/sphinx/source/content/FirstSteps.rst
- docs/sphinx/source/content/Installation.rst
- docs/sphinx/source/content/UsingThePlugin.rst
This PR aims at improving the doc :
- introducing ImGui everywhere in the examples
- keeping a mention about how to run Qt based GUI
- clarify the use of SOFA within a Python environment
>  Update documentation: ImGui, Qt, and Python env

- Plugin/src/SofaPython3/DataHelper.cpp
- Plugin/src/SofaPython3/DataHelper.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/tests/Simulation/Node.py
Add new python constructor for Node that takes as input a kwargs list of data values and set them at the the object creation. 
The method doing the data set is generic and thus could be applied to all the code base.
> Add Node constructor with kwargs
