- bindings/Sofa/tests/Core/BaseData.py
Just the test that goes with #7
> ADD test for Data DownCast

- Plugin/src/SofaPython3/Prefab.cpp
- bindings/Sofa/package/__init__.py
The most notable point is that I'm now right sure that we must drop the first "node" parameter.
> Various Fix in Prefab.

- bindings/Sofa/package/__init__.py
- bindings/Sofa/package/prefab.py
Fix context, docstring & prefab properties
- Move Sofa.Prefab in its own module in Sofa package
- ADD doc for Sofa.Prefab
- IMPROVE error handling for parent / parents protected keywords
- FIX docstring parameter from __doc__ and prefab params
> FIX prefab contructions helper

- Plugin/src/SofaPython3/DataHelper.h
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.h
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.h
The PR 1491 et 1504 merged in sofa prevent the plugin to compile.
This PR fix that.
> [FIX] broken plugin since Sofa PR #1491 & #1504

- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
Build is now passing on both Linux and MacOS
> [CI] Update workflows to use SOFA's nightly built packages

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
Added bindings for some methods of the BaseCamera object, based on the model of the already made "rotate" method binding.
> Added bindings for camera methods

- Plugin/src/SofaPython3/SceneLoaderPY3.cpp
.... from SceneLoaderPY3.cpp
(should be merged before #1848 from SOFA is merged)
> [Plugin] Remove useless ArgumentParser include

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.cpp
- bindings/Sofa/tests/Core/ForceField.py
- bindings/Sofa/tests/Core/MyRestShapeForceField.py
- bindings/Sofa/tests/Core/PythonRestShapeForceField.py
- examples/emptyForceField.py
- examples/example-forcefield.py
Cleaner merge history for #120.
> [ForceField] Specified template type for python classes

- Plugin/src/SofaPython3/Prefab.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseObject.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
This fix compilation issue resulting from #PR1794
> [SofaPython3] FIX for synchronization with sofa #PR1794

- Plugin/src/SofaPython3/Prefab.cpp
- Plugin/src/SofaPython3/PythonFactory.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseObject.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
> [SofaPython3] FIX for synchronization with sofa #PR1744

- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Quat.cpp
To stay synchronized with PR: https://github.com/sofa-framework/sofa/pull/1878
> [SofaTypes] FIX Binding_Quat to synchronize with change in Quater.h

- examples/liver-scriptcontroller.py
Adding an example with the liver and new spheres created when pressing the L key.
Useful to have an example when you need to create new object on the fly :
> [example] Add a new interactive scene, creating objects

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
> [Binding/Sofa.Core] Replace a std::cout with an exception.

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
Add bindings for the base camera function setDefaultView().
> [BaseCamera] add setDefaultView bindings

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ContactListener.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ContactListener_doc.h
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation_doc.h
Hi!
I added some functions that ease the use of the ContactListener in Python3. :)
I also added a step function to the simulation because I wanted to run n animate calls directly one after the other.
Tested the build against sofa/master and sofa/v21.12_beta.
Cheers,
Paul
> [Bindings] Utility bindings for ContactListener and Simulation

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/tests/Core/BaseLink.py
Components are now named consistently with XML scenes.
> [Sofa.Core] A helper class for consistent component naming

- .github/workflows/ci.yml
As discussed with @damienmarchal, this new `is_nightly` parameter will offer nightly binaries capabilities to the CI workflow.
> [CI] ADD is_nightly parameter

- bindings/Modules/src/SofaPython3/SofaDeformable/Binding_SpringForceField.cpp
- examples/springForceField.py
- [Add bindings for all data types supported by springForceField](https://github.com/sofa-framework/SofaPython3/commit/5fa25bd977ba20119219bb2bd93f9a73f530adf9)
- [Add scene showing an example of spring binding](https://github.com/sofa-framework/SofaPython3/commit/1aed9bd7a019adfddf76efc7add469c6d2b46efa)
> Add bindings for all data types supported by SpringForceField + example

- bindings/SofaGui/Bindings.SofaGuiConfig.cmake.in
- bindings/SofaGui/CMakeLists.txt
- bindings/SofaGui/src/SofaPython3/SofaGui/Binding_BaseGui.cpp
- bindings/SofaGui/src/SofaPython3/SofaGui/Binding_GUIManager.cpp
`SofaGuiCommon` is no longer in `SofaGui`, therefore it needs to be removed from the dependencies in CMakeLists.txt
> [SofaGui] Update GUI related modules

- bindings/CMakeLists.txt
- bindings/Sofa/CMakeLists.txt
I followed the same hierarchy than in the "bindings" folder
Before
After
> Organize targets into Bindings folder

- .github/workflows/ci.yml
Python 3.8 is the version used on SOFA CI.
> [CI] Consistent python version

- bindings/Modules/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaConstraintSolver/Binding_ConstraintSolver.cpp
- bindings/Modules/src/SofaPython3/SofaConstraintSolver/Binding_ConstraintSolver.h
- bindings/Modules/src/SofaPython3/SofaConstraintSolver/Binding_ConstraintSolver_doc.h
- bindings/Modules/src/SofaPython3/SofaConstraintSolver/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaConstraintSolver/Module_SofaConstraintSolver.cpp
- bindings/Modules/tests/CMakeLists.txt
- bindings/Modules/tests/SofaConstraintSolver/matrix_access.py
- bindings/Modules/tests/SofaLinearSolver/matrix_access.py
- bindings/Modules/tests/main.cpp
- examples/access_compliance_matrix.py
Following the work started in #260 and #262, this PR introduces a binding to access the compliance matrix in the constraint space, namely $W$
An example is provided
A simple unit test is added
> Binding to access to the compliance matrix in constraint space

- Plugin/CMakeLists.txt
Following https://github.com/sofa-framework/sofa/pull/3196 changes in SofaMacrosInstall
> [Plugin][CMake] Explicit RELOCATABLE parameter

- Plugin/src/SofaPython3/DataHelper.cpp
- Plugin/src/SofaPython3/Prefab.h
- Plugin/src/SofaPython3/PythonEnvironment.cpp
- Plugin/src/SofaPython3/PythonFactory.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataContainer.cpp
- bindings/Sofa/tests/Core/BaseData.py
This branch is based on the work done in #293 + extra commit.
> [all] Fix memory leak

- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.cpp
For some reasons, the conditional methods were not liked by pybind.
> [bindings.SofaTypes] Follow changes in Mat

- Plugin/src/SofaPython3/DataHelper.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
As the title says. :) 
Issue with information and instructions how to reproduce the problem: https://github.com/sofa-framework/SofaPython3/issues/303
Cheers,
Paul
> Memory leak when calling Sofa.Simulation.unload(root_node)

- CMakeLists.txt
- Plugin/CMakeLists.txt
- bindings/Modules/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaBaseTopology/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaConstraintSolver/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaDeformable/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaGL/CMakeLists.txt
- bindings/Modules/src/SofaPython3/SofaLinearSolver/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Components/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Helper/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Types/CMakeLists.txt
- bindings/SofaExporter/CMakeLists.txt
- bindings/SofaGui/CMakeLists.txt
- bindings/SofaRuntime/CMakeLists.txt
- bindings/SofaTypes/CMakeLists.txt
Related to https://github.com/sofa-framework/sofa/pull/3382
On my setup (msvc), reduce from 3.5s to less than 1s
> [CMake] Speed-up Configuration

- examples/.scene-tests
This is to avoid a timeout on the CI
> Lower number of steps in scene tests

- bindings/SofaGui/Bindings.SofaGuiConfig.cmake.in
Typo: Sofa.Gui :arrow_right: Sofa.GUI
> Update cmake.in to fix configuration step

- examples/ReadTheDocs_Example.py
- examples/example-forcefield.py
with VisualGrid and VisualAxis.
Due to https://github.com/sofa-framework/sofa/pull/3634/files
> [Examples] Replace usage of deprecated aliases OglGrid and OglAxis

- bindings/Modules/tests/SofaConstraintSolver/matrix_access.py
- examples/access_compliance_matrix.py
Depends on [#2777](https://github.com/sofa-framework/sofa/pull/2777)
> Deprecation of MappingGeometricStiffnessForceField

- Plugin/src/SofaPython3/DataHelper.cpp
To discuss: what to do if `nfo.size()` is zero?
> Prevent division by zero

- examples/CMakeLists.txt
- examples/ReadTheDocs_Example.py
- examples/access_compliance_matrix.py
- examples/access_mass_matrix.py
- examples/access_matrix.py
- examples/access_stiffness_matrix.py
- examples/additional-examples/ControllerScene.py
- examples/additional-examples/pygame_example.py
- examples/additional-examples/pyqt_example.py
- examples/advanced_timer.py
- examples/basic-addGUI.py
- examples/basic.py
- examples/emptyController.py
- examples/emptyDataEngine.py
- examples/emptyForceField.py
- examples/example-forcefield.py
- examples/example-scriptcontroller.py
- examples/keyEvents.py
- examples/liver-scriptcontroller.py
- examples/liver.py
- examples/loadXMLfromPython.py
- examples/pointSetTopologyModifier.py
- examples/springForceField.py
Cherry pick from #355 in master
> [examples] Fix all example warnings and add all files in CMakeLists

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_TaskScheduler.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_TaskScheduler.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_TaskScheduler_doc.h
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
- examples/taskScheduler.py
Example is provided (a cantilever beam). Example of output:
```
Number of threads #1
500 iterations computed in 8.066920757293701 seconds
Number of threads #2
500 iterations computed in 4.4411797523498535 seconds
Number of threads #3
500 iterations computed in 3.3134970664978027 seconds
Number of threads #4
500 iterations computed in 2.6986820697784424 seconds
Number of threads #5
500 iterations computed in 2.440063953399658 seconds
Number of threads #6
500 iterations computed in 2.3964955806732178 seconds
Number of threads #7
500 iterations computed in 2.0894110202789307 seconds
Number of threads #8
500 iterations computed in 2.2959535121917725 seconds
Stopping...
Stopped
```
> Binding to setup task scheduler (nb threads)

- bindings/Modules/tests/SofaConstraintSolver/matrix_access.py
- bindings/Sofa/tests/Core/ForceField.py
- examples/access_compliance_matrix.py
Consequence of the move of the csparse solvers in a plugin https://github.com/sofa-framework/sofa/pull/4258
> Replace csparse solvers by Eigen solvers

- .github/workflows/ci.yml
Change nightly release semantic to fit github
> [CI] FIX nightly artifact generation

- .github/workflows/ci.yml
The last fix resulted from the action output error. But in fact it seems that the problem was not the tag but the branch itself. 
Here I reverted the semantic change and just changed the input of the action. The semantic change might still be needed but I am not sure until this has been tested...
> Fix artifact generation

- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseMeshTopology.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Topology.cpp
- bindings/Sofa/tests/Core/BaseObject.py
+ a unit test
Fixes https://github.com/sofa-framework/sofa/issues/4335
> Fix BaseMeshTopology inheritance

- Testing/CMakeLists.txt
- Testing/src/SofaPython3Testing/PythonTest.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
- bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
- bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
https://github.com/sofa-framework/sofa/pull/4495
A binding need simpleapi API
> [SimpleApi] Apply simpleapi move to new library

- CMake/SofaPython3Tools.cmake
> Add headers to the library so they're visible in IDE

- docs/sphinx/source/menu/SofaPlugin.rst
I would like to automatize the doc generation as well here from what we did last time @damienmarchal 
I need to remember the steps to complete to generate it on readthedocs
> Update python version to 3.10 in doc

- Plugin/src/SofaPython3/Prefab.cpp
https://github.com/sofa-framework/sofa/pull/4827
> Follow SOFA change for init/updatevisual

- examples/access_compliance_matrix.py
- examples/access_matrix.py
- examples/access_stiffness_matrix.py
- examples/advanced_timer.py
- examples/liver-scriptcontroller.py
- examples/liver.py
- examples/loadXMLfromPython.py
- examples/springForceField.py
- examples/taskScheduler.py
All is in the title, let's make SP3 examples clean :sparkle:
> [examples] Fix warnings

- .github/workflows/ci.yml
https://github.com/sofa-framework/sofa/discussions/4979
> CI upload artifact version update

- bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
> Use DataTypeInfo to fix discrepancy on Vec<N,T> typename

- bindings/Sofa/tests/Core/Events.py
Needed for https://github.com/sofa-framework/sofa/pull/5052
> Fix Event test due to a missing plugin [Constraint]

- bindings/Modules/tests/SofaConstraintSolver/matrix_access.py
- bindings/Sofa/tests/Core/BaseLink.py
- bindings/Sofa/tests/Simulation/Node.py
Needed for https://github.com/sofa-framework/sofa/pull/5053
> Fix unit tests due to a missing plugin [Mapping]

- bindings/SofaGui/Bindings.SofaGuiConfig.cmake.in
- bindings/SofaGui/CMakeLists.txt
- bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
- examples/basic-addGUI.py
- examples/emptyController.py
- examples/emptyDataEngine.py
- examples/emptyForceField.py
- examples/example-forcefield.py
- examples/liver-scriptcontroller.py
- examples/liver.py
- examples/loadXMLfromPython.py
Superseded by https://github.com/sofa-framework/Sofa.Qt/pull/7 
Question: what to do with the scenes in `example/` using qt guis ? 🤔
> [SofaGui] Remove Sofa.Gui.Qt references

- docs/sphinx/source/content/FirstSteps.rst
Further to https://github.com/sofa-framework/sofa/discussions/5407
> [doc] Fix examples given in the First Steps

- package.nix
> Update version in package.nix

- examples/basic-addGUI.py
- examples/basic-useQtGUI.py
- examples/emptyController.py
- examples/emptyDataEngine.py
- examples/emptyForceField.py
- examples/example-forcefield.py
- examples/liver-scriptcontroller.py
- examples/liver.py
- examples/loadXMLfromPython.py
> [examples] Simplify use of ImGui

- examples/access_contact_forces.py
As it is expected from many users .. in addition to the scene access_constraint_matrix
> [Examples] Add a script to access contact forces
